is.stream: "Ваш статус \"Стримлю\""
is.rec: "Ваш статус \"Записываю\""
is.justplay: "Ваш статус \"Просто играю\""
set.stream: "Ваш статус установлен на \"Стримлю\""
set.rec: "Ваш статус установлен на \"Записываю\""
set.justplay: "Ваш статус установлен на \"Просто играю\""
papi.stream: "twitch"
papi.rec: "[REC]"
papi.justplay: "ХУЙ"